SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM LOJA_VIRTUAL_TEST_DB.PEDIDO_ITEM;
DELETE FROM LOJA_VIRTUAL_TEST_DB.PEDIDO;
DELETE FROM LOJA_VIRTUAL_TEST_DB.PRODUTO;
DELETE FROM LOJA_VIRTUAL_TEST_DB.CLIENTE;

SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE LOJA_VIRTUAL_TEST_DB.PEDIDO_ITEM AUTO_INCREMENT = 1;
ALTER TABLE LOJA_VIRTUAL_TEST_DB.PEDIDO AUTO_INCREMENT = 1;
ALTER TABLE LOJA_VIRTUAL_TEST_DB.PRODUTO AUTO_INCREMENT = 1;
ALTER TABLE LOJA_VIRTUAL_TEST_DB.CLIENTE AUTO_INCREMENT = 1;
