SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM PEDIDO_ITEM;
DELETE FROM PEDIDO;
DELETE FROM PRODUTO;
DELETE FROM CLIENTE;

SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE PEDIDO_ITEM AUTO_INCREMENT = 1;
ALTER TABLE PEDIDO AUTO_INCREMENT = 1;
ALTER TABLE PRODUTO AUTO_INCREMENT = 1;
ALTER TABLE CLIENTE AUTO_INCREMENT = 1;

--INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, PRECO, QUANTIDADE, FOTO, SIZE) 
--VALUES (1, 'CAMISA BRANCA', 'CAMISA BRANCA', '39.99', 6, NULL, 'M');
--INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, PRECO, QUANTIDADE, FOTO, SIZE) 
--VALUES (2, 'CAMISA AZUL', 'CAMISA AZUL', '32.39', 6, NULL, 'M');
--INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, PRECO, QUANTIDADE, FOTO, SIZE) 
--VALUES (3, 'CAMISA VERMELHA', 'CAMISA VERMELHA', '16.90', 6, NULL, 'M');
--INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, PRECO, QUANTIDADE, FOTO, SIZE) 
--VALUES (4, 'CAMISA PRETA', 'CAMISA PRETA', '42.99', 6, NULL, 'M');
--INSERT INTO PRODUTO (ID_PRODUTO, NOME, DESCRICAO, PRECO, QUANTIDADE, FOTO, SIZE) 
--VALUES (5, 'CAMISA VERDE', 'CAMISA VERDE', '16.99', 6, NULL, 'M');